library neon.globals;
import 'package:camera/camera.dart';
import 'package:flutter/cupertino.dart';
List array=[];
Color colors1;
List color=[];
List gradient1=[];
List gradient2=[];
Color colors2;
int f=0;
var a = AssetImage("images/neon.jpeg");
var b;
CameraController controller;
