library neon.globals1;

import 'package:camera/camera.dart';
import 'package:flutter/cupertino.dart';

List array = [];
List array8 = [];
Color colors1;
var user1;
List color = [];
List array1 = [];
List array2 = [];
String array5;
String name;
String email;
String imageUrl;
int k;
int l;
List gradient5 = [];
List gradient6 = [];
List color4 = [];
String image1;
String name2;
List userid = [];
var users4;
Future<List> colors3;
List image = [];
List name1 = [];
List gradient1 = [];
List gradient2 = [];
List gradient3 = [];
List gradient4 = [];
List time = [];
List username = [];
List username1 = [];
List username2 = [];
String index1;
String result5;
String boolean;
Color colors2;
int f = 0;
int f1 = 0;
int f2;
int h = 0;
int index2;
int index3;
String result4;
String result;
String result1;
String result2;
String result3;
String result6;
String result7;
List array3 = [];
List array4 = [];
var ab = AssetImage("images/neon.jpeg");
var b;
CameraController controller1;
List comment1 = [];
List comment2 = [];
List comment3 = [];
List comment4 = [];
List comment5 = [];
List comment6 = [];
List comment7 = [];
List comment8 = [];
List comment9 = [];
List comment10 = [];
List comment11 = [];
List comment12 = [];
List comment13 = [];
