library neon.globals1;
import 'package:camera/camera.dart';
import 'package:flutter/cupertino.dart';
List array=[];
Color colors1;
List color=[];
List array1=[];
List array2=[];
Future<List>colors3;
List image=[];
List name1=[];
List gradient1=[];
List gradient2=[];
List gradient3=[];
List gradient4=[];
Color colors2;
int f=0;
var a = AssetImage("images/neon.jpeg");
var b;
CameraController controller1;
